# Site settings
title: Yusuf Wadi
email: yusufwadi1@gmail.com
description: Neural Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
download_button_url: https://gitlab.com/andrewbanchich/fractal-jekyll-theme

collections:
  experience:
    sort_by: place
    order:
      - index.md
  projects:
    sort_by: place 
    order:
      - index.md
  skills:
    sort_by: place
    order:
      - index.md

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/yusuf-waedi
instagram_url: https://www.instagram.com/ywadi_/
linkedin_url: https://www.linkedin.com/in/yusuf-wadi
pinterest_url:
slack_url:

# Build settings
markdown: kramdown
