# Site settings
title: Yusuf Wadi
email: yusufwadi1@gmail.com
description: Neural Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
download_button_url: https://gitlab.com/andrewbanchich/fractal-jekyll-theme

collections:
  experience:
    sort_by: place
    order:
      - index.md
  gallery:
    sort_by: place 
    order:
      - index.md
  skills:
    sort_by: place
    order:
      - index.md

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
